### ISSUE TITLE
connection don't return complete response some times

### ISSUE THREAD

**Issue by martcpp** [little-bear-labs/intern-screener-2024-public#1]
the server send back incomplete json byte some times this cause program to crash when trying to deserialize json response
e.g 
`{"sender_id":"4adf00b0535cfb4a1aafd38b7c6f334bb7a79a812defbcbbfd76caa78ac83b26","receiver_id":"27f2ae764ff8c7ff3d673f6cc2a4182ed1614c1c128c0a3310dd194e4e578951",`

**Comment by martcpp** [comment]
also some time it return less and when i try to loop over it until the data in the json is complete my code never return any value
i have use python socket and also rust std::net crate .

**Comment by martcpp** [comment]
this is what i got using ncat `with ncat i was able to get this
`"sender_id":"322ed98ee6d88a9c92d0ddcbead6e2e061914835c3cfd740a16fbe1e97f029e9","receiver_id":"39d4f849434ccd4e8e69c296962a0afd7a19ae0c9626d07af6fd2ce8a85b03c8","msg_id":"","type":"init"}
{"sender_id":"39d4f849434ccd4e8e69c296962a0afd7a19ae0c9626d07af6fd2ce8a85b03c8","receiver_id":"322ed98ee6d88a9c92d0ddcbead6e2e061914835c3cfd740a16fbe1e97f029e9","msg_id":"","type":"query"}
{"sender_id":"322ed98ee6d88a9c92d0ddcbead6e2e061914835c3cfd740a16fbe1e97f029e9","receiver_id":"39d4f849434ccd4e8e69c296962a0afd7a19ae0c9626d07af6fd2ce8a85b03c8","msg_id":"","type":"neighbors","n":["4ca96f7b00d0cf63bb2d9c06f3995d0cc2b13fbd014d97de63607c6bc2e376d4","888b91f9503e9d7e8aa7ce564ced3f5d819e179a53adf8aafa4eb9a1a71db807","cd0c16386f1676d347c842afb4ee1091b645e46dc4551fdd85ce00d48b4fb494","2b304a348373445dbc8db0f2b659c292ee64c529b7d27534bdf55d11f717938e","bb13cd7c1e8c78a934903566945bb8771ba51aaa562d88f825b9a142c00f3dbe","0c10c7c1fc5eadd6f2bfc89d26cc7b2c204ce7ec4879fab1a6fc3a40ecc91ded","b2bafc71dccb9b4fe207100bf772670f73f0684a1f6abbf26974d1588ed00ae1","063f0b3b4c8641d8ebe1f51156073b260ea54fcbb68607f9b942595ce578d1c8","28b65ceec455076396eb4683e22b606d6c6b2e58230a3fd3ac3c8ee6ac6f51a0","6003fc4acdbcb9b385fb9a2aeb4e8db987d48043ca4a9b7b22ffae6d225461ea","7b65c20ce5f5e631929358ae2af8c35e7a7fde3c5e3c6bd06dd59f7cce4bd82a","f22ef81b02b288ac1d98f19fd40b921b58015e8c9f3f2a67fd306a2e701b2bab","5f3009e9408e986f382068e532551f0bb0eac9cca60ed8f79ef7ba1c57b00fbe","a23f64990eed5ed5e764b15ca5457c4b7847354b46d8eabd18db882ec7f8b712","9686a4a187d8fe1132f2b915f767106347a7dea3791b3ebdf21b1e58d3b44b53","86f2b41d49f0f59c0ef2ede4ffd573d3cc6867355732c89c026e6882aa80224d","e9d197694f43a27a8286e34325ae92fe944c61d901e893b2e8b20e13a06a935e","8684067d445f382fde078a80f14424e757ec3f807dc0e47b37c365471c4e2605","f1e2563f2bae03fd2a5b5cd795a2ce8e7fb2f370dc762d6e73c17d8c55594582","a203393b1024d6e67356a76589c854d4040a5811a60393752a77ea1cca269d8a","5f522885979b1e9917615b6b92aa22c26783db07f47ba00f96ae3c0dc2ed37aa","23a1492628907811564d4e24d03a3f1a72458c15e5d0c31393d46382cc0aa9dc","fd393f8e694caaf5680c0ed3e6591cfb89187deb64b1a3fe77e1dd646d9d99bc","3476253c079b840e935edd76e53b11c2d475b236f663d53424ebde31456a4bc2","a47813897cf8497f03327ae76a4935f4bbf863c2801a3c1cda666570f41a7427","02fb7622536f6f6a1b649936c9f75e75d09e3e85b01320de1fc41e35fde0fca1","c79848159e0077ba878762dd3055ba98f68e5c311e78ece739f6e526915b73bd","7af024517dba31484336e83ff46feee816035d1c6a2d1a0744b92d4d4798d024"]}`

`
@ckousik

**Comment by ckousik** [comment]
`ncat` is able to read a complete json response, therefore this seems like a read issue in your implementation
